<?php 
	$aArray_tipos_usos = array(
5 => 'ALQUILER SIN CHOFER'
,12 => 'AMBULANCIA DE TRASLADO'
,2 => 'COMERCIAL'
,13 => 'LOCAL'
,11 => 'NO RURAL'
,3 => 'OFICIAL'
,1 => 'PARTICULAR'
,8 => 'REMIS'
,10 => 'RURAL'
,6 => 'SERVICIO ESCOLAR'
,9 => 'SERVICIO ESPECIAL'
,16 => 'SERVICIO ESPECIAL EXCLUSIVO'
,4 => 'SERVICIO FUNEBRE'
,7 => 'TAXI'
,15 => 'TTE PASAJEROS/SERV ESPC'
,14 => 'TTE RURAL PASAJEROS'
);
?>