<?php 
	$aArray_tipos_polizas = array(
1 => 'AUTOMOTORE'
,2 => 'ACCIDENTE PERSONALES'
,3 => 'SEGURO TECNICO'
,4 => 'RIESGO INCENDIO'
,5 => 'INTEGRAL DE COMERCIO'
,6 => 'INTEGRAL DE CONSORCIO'
,7 => 'RESPONS. CIVIL COMPRENSIVA'
,8 => 'COMBINADO FAMILIAR'
,9 => 'EMBARCACION DE PLACER'
);
?>