<p>Entre GRIVA S.R.L. (en adelante &ldquo;GRIVA&rdquo;), con domicilio especial en calle 12 de Octubre N&deg; 832, de la ciudad de Salta; por una parte y por la otra parte la persona cuyo nombre, apellido, tipo y N&deg; de documento y dem&aacute;s datos personales, se aclaran al final de este documento, (en adelante &rdquo;TITULAR&rdquo;), convienen celebrar este contrato cuyos t&eacute;rminos y condiciones regir&aacute;n &nbsp;la emisi&oacute;n y utilizaci&oacute;n de la credencial de identificaci&oacute;n como cliente de GRIVA y &nbsp;todas las compras y transacciones financiadas por GRIVA que efect&uacute;e el titular mientras se encuentre vigente; todo ello de conformidad con las siguientes cl&aacute;usulas y condiciones:</p>
<p>
	<strong>PRIMERA:</strong> El titular autoriza a GRIVA&nbsp; a emitir a su nombre una &ldquo;Tarjeta de promoci&oacute;n&rdquo;, gratuita y sin costo de mantenimiento, cuya &uacute;nica finalidad ser&aacute; identificarlo como cliente de GRIVA, con la que&nbsp; podr&aacute; acceder a importantes promociones y operar efectuando compras o contratando servicios en Comercios Adheridos al sistema GRIVA.-</p>
<p>
	<strong>SEGUNDA:</strong> Por cada compra que efect&uacute;e el titular se emitir&aacute; la correspondiente factura por el precio total de dicha transacci&oacute;n. En los casos en que el pago del producto o servicio adquirido se convenga en cuotas, el titular suscribir&aacute; un pagar&eacute; con la cl&aacute;usula &ldquo;sin protesto&rdquo;, a la orden de GRIVA &nbsp;por la suma total de la compra.-</p>
<p>
	<strong>TERCERA:</strong> El importe de cada compra que sea financiada por GRIVA&nbsp; ser&aacute; abonado por el titular en el domicilio de GRIVA o en los lugares expresamente autorizados, en la cantidad de cuotas mensuales, consecutivas y por el importe, fechas de vencimiento e inter&eacute;s que en cada caso se pacte, suscribi&eacute;ndose al efecto un cronograma de vencimiento de cuota con los datos esenciales.-</p>
<p>
	<strong>CUARTA:</strong> En caso de incumplimiento &nbsp;en el pago de una sola de las cuotas acordadas se producir&aacute; la mora y la caducidad de los plazos en forma autom&aacute;tica, de pleno derecho y sin necesidad de intimaci&oacute;n judicial o extrajudicial alguna. &ndash;</p>
<p>
	<strong>QUINTA:</strong> Para acreditar el pago, solo tendr&aacute; validez el resumen de cuenta con el C&oacute;digo de Barra GRIVA de Seguridad enviado v&iacute;a correo&nbsp; y/o e-mail con firma y sello de cajero habilitado o recibo oficial emitido por sistema de GRIVA.-&nbsp;</p>
<p>
	<strong>SEXTA:</strong> GRIVA podr&aacute; en cualquier momento, y sin necesidad de previa autorizaci&oacute;n adicional o conocimiento previo del titular, ceder en todo o en parte sus cr&eacute;ditos contra el titular por cualquiera de los medios previstos por la ley, inclusive por la ley 24.441.-</p>
<p>
	<strong>SEPTIMA: </strong>GRIVA es ajeno a la relaci&oacute;n concertada con los Comercios adheridos al sistema GRIVA por la compra y/o contrataci&oacute;n de servicios que se abonen mediante la tarjeta y no responde por las obligaciones de los mismos ni por las consecuencias que puedan ocasionarse a ra&iacute;z de tales contrataciones. Por lo que el Titular no podr&aacute; negar o supeditar el pago correspondiente a GRIVA, por problemas con el bien adquirido y/o servicio contratado. El reclamo al establecimiento comercial adherido ser&aacute; de su exclusiva responsabilidad. &nbsp;</p>
<p>
	<strong>OCTAVA: </strong>En caso de controversia las partes se someter&aacute;n a la jurisdicci&oacute;n de los tribunales ordinarios correspondiente a la ciudad de Salta Capital, con renuncia a cualquier otro fuero o jurisdicci&oacute;n que les pudiere corresponder. A todos los efectos extrajudiciales y judiciales, tanto GRIVA como el titular y sus codeudores constituyen domicilios especiales en los indicados en este acuerdo, teni&eacute;ndose por validas todas las notificaciones que se cursen en los mismos.-</p>